"""
Training Script for Attention U-Net KDA Prediction.

Trains the Attention U-Net model to predict Key Diagnostic Areas (KDA)
from nuclear segmentation masks generated by AFN-DeSeg.

Usage:
    python training/kda_trainer.py \
        --data_dir /path/to/kda_data \
        --output_dir ./checkpoints/kda \
        --epochs 100
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm

# Add project root to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from models.attention_unet import AttentionUNet


# =============================================================================
# Loss Functions
# =============================================================================

class DiceLoss(nn.Module):
    """
    Dice Loss for binary segmentation.

    Dice = 2 * |X ∩ Y| / (|X| + |Y|)
    Loss = 1 - Dice

    Args:
        smooth: Smoothing factor to avoid division by zero.
    """

    def __init__(self, smooth: float = 1e-6):
        super(DiceLoss, self).__init__()
        self.smooth = smooth

    def forward(
        self,
        pred: torch.Tensor,
        target: torch.Tensor
    ) -> torch.Tensor:
        """
        Compute Dice loss.

        Args:
            pred: Predicted probabilities, shape (B, 1, H, W).
            target: Ground truth mask, shape (B, 1, H, W).

        Returns:
            Dice loss value.
        """
        pred_flat = pred.view(-1)
        target_flat = target.view(-1)

        intersection = (pred_flat * target_flat).sum()
        union = pred_flat.sum() + target_flat.sum()

        dice = (2.0 * intersection + self.smooth) / (union + self.smooth)
        return 1.0 - dice


class CombinedLoss(nn.Module):
    """
    Combined BCE + Dice Loss for KDA prediction.

    L_total = bce_weight * BCE + dice_weight * Dice

    Args:
        bce_weight: Weight for BCE loss.
        dice_weight: Weight for Dice loss.
    """

    def __init__(
        self,
        bce_weight: float = 1.0,
        dice_weight: float = 1.0
    ):
        super(CombinedLoss, self).__init__()

        self.bce_weight = bce_weight
        self.dice_weight = dice_weight

        self.bce_loss = nn.BCELoss()
        self.dice_loss = DiceLoss()

    def forward(
        self,
        pred: torch.Tensor,
        target: torch.Tensor
    ) -> Tuple[torch.Tensor, Dict[str, float]]:
        """
        Compute combined loss.

        Args:
            pred: Predicted probabilities.
            target: Ground truth mask.

        Returns:
            Tuple of (total_loss, loss_dict).
        """
        bce = self.bce_loss(pred, target)
        dice = self.dice_loss(pred, target)

        total = self.bce_weight * bce + self.dice_weight * dice

        loss_dict = {
            'bce': bce.item(),
            'dice': dice.item(),
            'total': total.item()
        }

        return total, loss_dict


# =============================================================================
# Dataset
# =============================================================================

class KDADataset(Dataset):
    """
    Dataset for KDA prediction training.

    Loads nuclear segmentation masks and corresponding KDA annotations.

    Args:
        data_dir: Directory containing the data.
        split: Data split ('train', 'val', 'test').
        transform: Optional transforms to apply.
    """

    def __init__(
        self,
        data_dir: str,
        split: str = 'train',
        transform: Optional[callable] = None
    ):
        self.data_dir = Path(data_dir)
        self.split = split
        self.transform = transform

        # Paths to data subdirectories
        self.masks_dir = self.data_dir / 'nuclear_masks'
        self.kda_dir = self.data_dir / 'kda_annotations'

        # Load file list
        self.samples = self._load_samples()

    def _load_samples(self) -> List[Tuple[Path, Path]]:
        """Load list of sample pairs (mask, kda)."""
        samples = []

        # Try to load split file
        split_file = self.data_dir / f'{self.split}.txt'
        if split_file.exists():
            with open(split_file, 'r') as f:
                filenames = [line.strip() for line in f if line.strip()]
        else:
            # Use all files
            filenames = [p.stem for p in self.masks_dir.glob('*.npy')]
            # Simple split
            n = len(filenames)
            if self.split == 'train':
                filenames = filenames[:int(0.7 * n)]
            elif self.split == 'val':
                filenames = filenames[int(0.7 * n):int(0.85 * n)]
            else:
                filenames = filenames[int(0.85 * n):]

        for name in filenames:
            mask_path = self.masks_dir / f'{name}.npy'
            kda_path = self.kda_dir / f'{name}.npy'

            if mask_path.exists() and kda_path.exists():
                samples.append((mask_path, kda_path))

        return samples

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor]:
        mask_path, kda_path = self.samples[idx]

        # Load data
        mask = np.load(mask_path).astype(np.float32)
        kda = np.load(kda_path).astype(np.float32)

        # Ensure binary
        mask = (mask > 0.5).astype(np.float32)
        kda = (kda > 0.5).astype(np.float32)

        # Apply transforms
        if self.transform is not None:
            augmented = self.transform(image=mask, mask=kda)
            mask = augmented['image']
            kda = augmented['mask']

        # Convert to tensor
        mask = torch.from_numpy(mask).unsqueeze(0)  # (1, H, W)
        kda = torch.from_numpy(kda).unsqueeze(0)    # (1, H, W)

        return mask, kda


# =============================================================================
# Trainer
# =============================================================================

class KDATrainer:
    """
    Trainer for Attention U-Net KDA prediction model.

    Handles training loop, validation, checkpointing, and logging.

    Args:
        model: AttentionUNet instance.
        train_loader: DataLoader for training data.
        val_loader: DataLoader for validation data.
        config: Training configuration dictionary.
        device: Device for training.
    """

    def __init__(
        self,
        model: AttentionUNet,
        train_loader: DataLoader,
        val_loader: DataLoader,
        config: Dict,
        device: torch.device
    ):
        self.model = model.to(device)
        self.train_loader = train_loader
        self.val_loader = val_loader
        self.config = config
        self.device = device

        # Loss function
        self.criterion = CombinedLoss(
            bce_weight=config.get('bce_weight', 1.0),
            dice_weight=config.get('dice_weight', 1.0)
        )

        # Optimizer
        self.optimizer = optim.Adam(
            model.parameters(),
            lr=config.get('learning_rate', 1e-4),
            weight_decay=config.get('weight_decay', 1e-5)
        )

        # Learning rate scheduler
        self.scheduler = optim.lr_scheduler.ReduceLROnPlateau(
            self.optimizer,
            mode='min',
            patience=config.get('scheduler_patience', 10),
            factor=0.5,
            min_lr=1e-7
        )

        # Training state
        self.current_epoch = 0
        self.best_val_loss = float('inf')
        self.best_val_dice = 0.0
        self.early_stop_counter = 0
        self.history = {
            'train_loss': [],
            'val_loss': [],
            'val_dice': [],
            'learning_rate': []
        }

    def train_epoch(self) -> Dict[str, float]:
        """
        Train for one epoch.

        Returns:
            Dictionary of training metrics.
        """
        self.model.train()
        total_loss = 0.0
        total_bce = 0.0
        total_dice = 0.0
        num_batches = 0

        pbar = tqdm(self.train_loader, desc=f"Epoch {self.current_epoch + 1} [Train]")

        for batch_idx, (masks, kda_targets) in enumerate(pbar):
            masks = masks.to(self.device)
            kda_targets = kda_targets.to(self.device)

            # Forward pass
            self.optimizer.zero_grad()
            predictions = self.model(masks)

            # Compute loss
            loss, loss_dict = self.criterion(predictions, kda_targets)

            # Backward pass
            loss.backward()

            # Gradient clipping
            torch.nn.utils.clip_grad_norm_(
                self.model.parameters(),
                max_norm=self.config.get('grad_clip', 1.0)
            )

            self.optimizer.step()

            # Accumulate metrics
            total_loss += loss_dict['total']
            total_bce += loss_dict['bce']
            total_dice += loss_dict['dice']
            num_batches += 1

            # Update progress bar
            pbar.set_postfix({
                'loss': f"{loss_dict['total']:.4f}",
                'dice_loss': f"{loss_dict['dice']:.4f}"
            })

        metrics = {
            'loss': total_loss / num_batches,
            'bce': total_bce / num_batches,
            'dice_loss': total_dice / num_batches
        }

        return metrics

    def validate(self) -> Dict[str, float]:
        """
        Validate on validation set.

        Returns:
            Dictionary of validation metrics.
        """
        self.model.eval()
        total_loss = 0.0
        total_dice_score = 0.0
        num_batches = 0

        with torch.no_grad():
            pbar = tqdm(self.val_loader, desc=f"Epoch {self.current_epoch + 1} [Val]")

            for masks, kda_targets in pbar:
                masks = masks.to(self.device)
                kda_targets = kda_targets.to(self.device)

                predictions = self.model(masks)
                loss, loss_dict = self.criterion(predictions, kda_targets)

                # Compute Dice score (1 - Dice loss)
                dice_score = 1.0 - loss_dict['dice']

                total_loss += loss_dict['total']
                total_dice_score += dice_score
                num_batches += 1

                pbar.set_postfix({
                    'loss': f"{loss_dict['total']:.4f}",
                    'dice': f"{dice_score:.4f}"
                })

        metrics = {
            'loss': total_loss / num_batches,
            'dice': total_dice_score / num_batches
        }

        return metrics

    def train(
        self,
        num_epochs: int,
        output_dir: str,
        save_every: int = 10
    ):
        """
        Full training loop.

        Args:
            num_epochs: Number of training epochs.
            output_dir: Directory to save checkpoints.
            save_every: Save checkpoint every N epochs.
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        patience = self.config.get('patience', 20)

        print(f"Starting training for {num_epochs} epochs")
        print(f"Device: {self.device}")
        print(f"Model parameters: {self.model.get_num_parameters():,}")

        for epoch in range(num_epochs):
            self.current_epoch = epoch

            # Train
            train_metrics = self.train_epoch()

            # Validate
            val_metrics = self.validate()

            # Update scheduler
            self.scheduler.step(val_metrics['loss'])
            current_lr = self.optimizer.param_groups[0]['lr']

            # Log metrics
            self.history['train_loss'].append(train_metrics['loss'])
            self.history['val_loss'].append(val_metrics['loss'])
            self.history['val_dice'].append(val_metrics['dice'])
            self.history['learning_rate'].append(current_lr)

            print(f"\nEpoch {epoch + 1}/{num_epochs}")
            print(f"  Train Loss: {train_metrics['loss']:.4f}")
            print(f"  Val Loss: {val_metrics['loss']:.4f}, Val Dice: {val_metrics['dice']:.4f}")
            print(f"  Learning Rate: {current_lr:.2e}")

            # Save best model
            is_best = val_metrics['dice'] > self.best_val_dice
            if is_best:
                self.best_val_dice = val_metrics['dice']
                self.best_val_loss = val_metrics['loss']
                self.early_stop_counter = 0

                self._save_checkpoint(
                    output_dir / 'kda_best.pth',
                    is_best=True
                )
                print(f"  New best model saved! Dice: {self.best_val_dice:.4f}")
            else:
                self.early_stop_counter += 1

            # Save periodic checkpoint
            if (epoch + 1) % save_every == 0:
                self._save_checkpoint(
                    output_dir / f'kda_epoch_{epoch + 1}.pth'
                )

            # Early stopping
            if self.early_stop_counter >= patience:
                print(f"\nEarly stopping triggered after {patience} epochs without improvement")
                break

        # Save final model
        self._save_checkpoint(output_dir / 'kda_final.pth')

        # Save training history
        with open(output_dir / 'training_history.json', 'w') as f:
            json.dump(self.history, f, indent=2)

        print(f"\nTraining completed!")
        print(f"Best validation Dice: {self.best_val_dice:.4f}")

    def _save_checkpoint(
        self,
        path: Path,
        is_best: bool = False
    ):
        """Save model checkpoint."""
        checkpoint = {
            'model_state_dict': self.model.state_dict(),
            'optimizer_state_dict': self.optimizer.state_dict(),
            'scheduler_state_dict': self.scheduler.state_dict(),
            'epoch': self.current_epoch,
            'best_val_loss': self.best_val_loss,
            'best_val_dice': self.best_val_dice,
            'config': self.config
        }
        torch.save(checkpoint, path)


# =============================================================================
# CLI
# =============================================================================

def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description='Train Attention U-Net for KDA Prediction'
    )

    # Data
    parser.add_argument('--data_dir', type=str, required=True,
                        help='Path to KDA training data')
    parser.add_argument('--output_dir', type=str, default='./checkpoints/kda',
                        help='Output directory for checkpoints')

    # Model
    parser.add_argument('--base_filters', type=int, default=64,
                        help='Base filter count')
    parser.add_argument('--attention_filters', type=int, default=256,
                        help='Attention gate filter count')
    parser.add_argument('--dropout', type=float, default=0.1,
                        help='Dropout rate')

    # Training
    parser.add_argument('--epochs', type=int, default=100,
                        help='Number of training epochs')
    parser.add_argument('--batch_size', type=int, default=8,
                        help='Batch size')
    parser.add_argument('--lr', type=float, default=1e-4,
                        help='Learning rate')
    parser.add_argument('--weight_decay', type=float, default=1e-5,
                        help='Weight decay')
    parser.add_argument('--patience', type=int, default=20,
                        help='Early stopping patience')

    # Loss weights
    parser.add_argument('--bce_weight', type=float, default=1.0,
                        help='BCE loss weight')
    parser.add_argument('--dice_weight', type=float, default=1.0,
                        help='Dice loss weight')

    # Other
    parser.add_argument('--num_workers', type=int, default=4,
                        help='DataLoader workers')
    parser.add_argument('--device', type=str, default=None,
                        help='Device (cuda/cpu)')
    parser.add_argument('--seed', type=int, default=42,
                        help='Random seed')

    return parser.parse_args()


def main():
    """Entry point for KDA model training."""
    args = parse_args()

    # Set seed
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    # Device
    if args.device is None:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    else:
        device = torch.device(args.device)

    print(f"Using device: {device}")

    # Config
    config = {
        'learning_rate': args.lr,
        'weight_decay': args.weight_decay,
        'bce_weight': args.bce_weight,
        'dice_weight': args.dice_weight,
        'patience': args.patience,
        'scheduler_patience': 10,
        'grad_clip': 1.0
    }

    # Model
    model = AttentionUNet(
        in_channels=1,
        base_filters=args.base_filters,
        attention_filters=args.attention_filters,
        dropout=args.dropout
    )

    print(f"Model parameters: {model.get_num_parameters():,}")

    # Datasets
    train_dataset = KDADataset(args.data_dir, split='train')
    val_dataset = KDADataset(args.data_dir, split='val')

    print(f"Training samples: {len(train_dataset)}")
    print(f"Validation samples: {len(val_dataset)}")

    # DataLoaders
    train_loader = DataLoader(
        train_dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=True
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=True
    )

    # Trainer
    trainer = KDATrainer(
        model=model,
        train_loader=train_loader,
        val_loader=val_loader,
        config=config,
        device=device
    )

    # Train
    trainer.train(
        num_epochs=args.epochs,
        output_dir=args.output_dir
    )


if __name__ == '__main__':
    main()
