"""
Attention U-Net for Key Diagnostic Area (KDA) Prediction.

This module implements an Attention U-Net architecture for identifying
high-tumor-burden regions (Key Diagnostic Areas) from nuclear segmentation
masks generated by AFN-DeSeg.

The architecture integrates attention gates in the skip connections to
focus on diagnostically relevant regions while suppressing background.

Reference:
    Oktay et al., "Attention U-Net: Learning Where to Look for the Pancreas"
    MIDL 2018
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Dict, List, Optional, Tuple

from .attention_gate import AttentionGate


class ConvBlock(nn.Module):
    """
    Double convolution block used in U-Net encoder and decoder.

    Structure: Conv -> BN -> ReLU -> Conv -> BN -> ReLU

    Args:
        in_channels: Number of input channels.
        out_channels: Number of output channels.
        dropout: Dropout rate (default: 0.0).
    """

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        dropout: float = 0.0
    ):
        super(ConvBlock, self).__init__()

        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Dropout2d(dropout) if dropout > 0 else nn.Identity(),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Dropout2d(dropout) if dropout > 0 else nn.Identity()
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.conv(x)


class EncoderBlock(nn.Module):
    """
    Encoder block: ConvBlock followed by MaxPool for downsampling.

    Args:
        in_channels: Number of input channels.
        out_channels: Number of output channels.
        dropout: Dropout rate.
    """

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        dropout: float = 0.0
    ):
        super(EncoderBlock, self).__init__()

        self.conv = ConvBlock(in_channels, out_channels, dropout)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Returns:
            Tuple of (pooled features, skip connection features).
        """
        features = self.conv(x)
        pooled = self.pool(features)
        return pooled, features


class DecoderBlock(nn.Module):
    """
    Decoder block with attention-gated skip connections.

    Structure: Upsample -> Attention Gate -> Concat -> ConvBlock

    Args:
        in_channels: Number of input channels from previous decoder level.
        skip_channels: Number of channels from encoder skip connection.
        out_channels: Number of output channels.
        attention_channels: Intermediate channels for attention gate.
        dropout: Dropout rate.
    """

    def __init__(
        self,
        in_channels: int,
        skip_channels: int,
        out_channels: int,
        attention_channels: int = 256,
        dropout: float = 0.0
    ):
        super(DecoderBlock, self).__init__()

        # Transposed convolution for upsampling
        self.upsample = nn.ConvTranspose2d(
            in_channels,
            in_channels // 2,
            kernel_size=2,
            stride=2
        )

        # Attention gate for filtering skip connection features
        self.attention_gate = AttentionGate(
            F_g=in_channels // 2,  # Gating signal channels
            F_l=skip_channels,      # Encoder feature channels
            F_int=attention_channels
        )

        # Convolution block after concatenation
        self.conv = ConvBlock(
            in_channels // 2 + skip_channels,
            out_channels,
            dropout
        )

    def forward(
        self,
        x: torch.Tensor,
        skip: torch.Tensor
    ) -> torch.Tensor:
        """
        Args:
            x: Features from previous decoder level.
            skip: Features from corresponding encoder level.

        Returns:
            Decoded features with attention-weighted skip connection.
        """
        # Upsample decoder features
        x = self.upsample(x)

        # Handle size mismatch due to odd dimensions
        if x.shape[2:] != skip.shape[2:]:
            x = F.interpolate(x, size=skip.shape[2:], mode='bilinear', align_corners=True)

        # Apply attention gate to skip connection
        skip_attended = self.attention_gate(g=x, x=skip)

        # Concatenate and convolve
        concat = torch.cat([x, skip_attended], dim=1)
        output = self.conv(concat)

        return output


class AttentionUNet(nn.Module):
    """
    Attention U-Net for Key Diagnostic Area (KDA) prediction.

    Takes binary nuclear segmentation masks as input and predicts
    regions with high tumor burden for diagnostic purposes.

    Architecture:
        - Encoder: 4 down-sampling blocks (64 -> 128 -> 256 -> 512)
        - Bottleneck: 512 -> 1024
        - Decoder: 4 up-sampling blocks with Attention Gates
        - Output: Single-channel probability map

    Args:
        in_channels: Input channels (1 for binary mask).
        base_filters: Number of filters in first layer (default: 64).
        num_classes: Output channels (1 for binary KDA).
        attention_filters: Intermediate channels in attention gates.
        dropout: Dropout rate (default: 0.1).
        deep_supervision: Enable deep supervision outputs (default: False).

    Example:
        >>> model = AttentionUNet(in_channels=1, base_filters=64)
        >>> x = torch.randn(2, 1, 512, 512)
        >>> output = model(x)
        >>> output.shape
        torch.Size([2, 1, 512, 512])
    """

    def __init__(
        self,
        in_channels: int = 1,
        base_filters: int = 64,
        num_classes: int = 1,
        attention_filters: int = 256,
        dropout: float = 0.1,
        deep_supervision: bool = False
    ):
        super(AttentionUNet, self).__init__()

        self.in_channels = in_channels
        self.base_filters = base_filters
        self.num_classes = num_classes
        self.deep_supervision = deep_supervision

        # Channel progression: 64 -> 128 -> 256 -> 512 -> 1024
        filters = [base_filters * (2 ** i) for i in range(5)]

        # Encoder path
        self.encoder1 = EncoderBlock(in_channels, filters[0], dropout=0)
        self.encoder2 = EncoderBlock(filters[0], filters[1], dropout=0)
        self.encoder3 = EncoderBlock(filters[1], filters[2], dropout=dropout)
        self.encoder4 = EncoderBlock(filters[2], filters[3], dropout=dropout)

        # Bottleneck
        self.bottleneck = ConvBlock(filters[3], filters[4], dropout=dropout)

        # Decoder path with attention gates
        self.decoder4 = DecoderBlock(
            filters[4], filters[3], filters[3],
            attention_filters, dropout
        )
        self.decoder3 = DecoderBlock(
            filters[3], filters[2], filters[2],
            attention_filters, dropout
        )
        self.decoder2 = DecoderBlock(
            filters[2], filters[1], filters[1],
            attention_filters // 2, dropout=0
        )
        self.decoder1 = DecoderBlock(
            filters[1], filters[0], filters[0],
            attention_filters // 4, dropout=0
        )

        # Output layer
        self.output_conv = nn.Conv2d(filters[0], num_classes, kernel_size=1)
        self.output_activation = nn.Sigmoid()

        # Deep supervision outputs (optional)
        if deep_supervision:
            self.ds_conv4 = nn.Conv2d(filters[3], num_classes, kernel_size=1)
            self.ds_conv3 = nn.Conv2d(filters[2], num_classes, kernel_size=1)
            self.ds_conv2 = nn.Conv2d(filters[1], num_classes, kernel_size=1)

        # Initialize weights
        self._init_weights()

    def _init_weights(self):
        """Initialize network weights."""
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.ConvTranspose2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)

    def forward(
        self,
        x: torch.Tensor
    ) -> torch.Tensor:
        """
        Forward pass through Attention U-Net.

        Args:
            x: Input nuclear mask, shape (B, 1, H, W).
               Values should be in [0, 1] range.

        Returns:
            KDA probability map, shape (B, 1, H, W).
            Values in [0, 1] representing KDA probability.
        """
        # Store input size for potential resizing
        input_size = x.shape[2:]

        # Encoder path
        x, skip1 = self.encoder1(x)   # -> (B, 64, H/2, W/2)
        x, skip2 = self.encoder2(x)   # -> (B, 128, H/4, W/4)
        x, skip3 = self.encoder3(x)   # -> (B, 256, H/8, W/8)
        x, skip4 = self.encoder4(x)   # -> (B, 512, H/16, W/16)

        # Bottleneck
        x = self.bottleneck(x)         # -> (B, 1024, H/16, W/16)

        # Decoder path with attention-gated skip connections
        x = self.decoder4(x, skip4)    # -> (B, 512, H/8, W/8)
        x = self.decoder3(x, skip3)    # -> (B, 256, H/4, W/4)
        x = self.decoder2(x, skip2)    # -> (B, 128, H/2, W/2)
        x = self.decoder1(x, skip1)    # -> (B, 64, H, W)

        # Output
        output = self.output_conv(x)
        output = self.output_activation(output)

        # Ensure output matches input size
        if output.shape[2:] != input_size:
            output = F.interpolate(output, size=input_size, mode='bilinear', align_corners=True)

        return output

    def forward_with_attention(
        self,
        x: torch.Tensor
    ) -> Tuple[torch.Tensor, Dict[str, torch.Tensor]]:
        """
        Forward pass with attention map extraction for visualization.

        Args:
            x: Input nuclear mask, shape (B, 1, H, W).

        Returns:
            Tuple of (output, attention_maps).
            attention_maps is a dict with attention coefficients from each level.
        """
        input_size = x.shape[2:]
        attention_maps = {}

        # Encoder
        x, skip1 = self.encoder1(x)
        x, skip2 = self.encoder2(x)
        x, skip3 = self.encoder3(x)
        x, skip4 = self.encoder4(x)

        # Bottleneck
        x = self.bottleneck(x)

        # Decoder with attention extraction
        x_up = self.decoder4.upsample(x)
        if x_up.shape[2:] != skip4.shape[2:]:
            x_up = F.interpolate(x_up, size=skip4.shape[2:], mode='bilinear', align_corners=True)
        attention_maps['level4'] = self.decoder4.attention_gate.get_attention_map(x_up, skip4)
        x = self.decoder4(x, skip4)

        x_up = self.decoder3.upsample(x)
        if x_up.shape[2:] != skip3.shape[2:]:
            x_up = F.interpolate(x_up, size=skip3.shape[2:], mode='bilinear', align_corners=True)
        attention_maps['level3'] = self.decoder3.attention_gate.get_attention_map(x_up, skip3)
        x = self.decoder3(x, skip3)

        x_up = self.decoder2.upsample(x)
        if x_up.shape[2:] != skip2.shape[2:]:
            x_up = F.interpolate(x_up, size=skip2.shape[2:], mode='bilinear', align_corners=True)
        attention_maps['level2'] = self.decoder2.attention_gate.get_attention_map(x_up, skip2)
        x = self.decoder2(x, skip2)

        x_up = self.decoder1.upsample(x)
        if x_up.shape[2:] != skip1.shape[2:]:
            x_up = F.interpolate(x_up, size=skip1.shape[2:], mode='bilinear', align_corners=True)
        attention_maps['level1'] = self.decoder1.attention_gate.get_attention_map(x_up, skip1)
        x = self.decoder1(x, skip1)

        # Output
        output = self.output_conv(x)
        output = self.output_activation(output)

        if output.shape[2:] != input_size:
            output = F.interpolate(output, size=input_size, mode='bilinear', align_corners=True)

        return output, attention_maps

    def get_num_parameters(self, trainable_only: bool = True) -> int:
        """
        Get the number of parameters in the model.

        Args:
            trainable_only: If True, count only trainable parameters.

        Returns:
            Number of parameters.
        """
        if trainable_only:
            return sum(p.numel() for p in self.parameters() if p.requires_grad)
        return sum(p.numel() for p in self.parameters())


def create_attention_unet(
    in_channels: int = 1,
    base_filters: int = 64,
    num_classes: int = 1,
    checkpoint_path: Optional[str] = None,
    device: str = 'cpu',
    **kwargs
) -> AttentionUNet:
    """
    Factory function to create Attention U-Net model.

    Args:
        in_channels: Input channels.
        base_filters: Base filter count.
        num_classes: Output classes.
        checkpoint_path: Path to pretrained checkpoint.
        device: Device to load model on.
        **kwargs: Additional arguments for AttentionUNet.

    Returns:
        Configured AttentionUNet instance.

    Example:
        >>> model = create_attention_unet(checkpoint_path='kda_best.pth')
        >>> model.eval()
    """
    model = AttentionUNet(
        in_channels=in_channels,
        base_filters=base_filters,
        num_classes=num_classes,
        **kwargs
    )

    if checkpoint_path is not None:
        checkpoint = torch.load(checkpoint_path, map_location=device)

        if 'model_state_dict' in checkpoint:
            model.load_state_dict(checkpoint['model_state_dict'])
        else:
            model.load_state_dict(checkpoint)

        print(f"Loaded checkpoint from {checkpoint_path}")

    model = model.to(device)

    return model


# Alias for backward compatibility
KDAAttentionUNet = AttentionUNet
